### ISSUE TITLE
VZD: Update Lat/Long Crash Fields

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-vz-data#134]
#### Lat/Lon Columns
- CRIS
- Geocoded (e.g. Here)
- Primary

#### GIS QA Status
- [x] 1 = Copied from CRIS to Primary
- [x] 2 = Copied from geocoder provider Primary
- [x] 3 = Entered manually to Primary

#### TODO
- [x] rename `_confirmed` lat/lon field to `_primary`
- [x] update data in DB so that;
    - [x] When CRIS is present, populate values to Primary column
    - [x] When Geocoded is present, populate value to Primary
    - [x] When manually entered, populate that value to Primary
- [x] create trigger to update fields as described above

**Comment by sergiogcx** [comment]
This is done:

- On UPDATE, the trigger first creates a history record. Then updates the lat-longs for primary based on the above logic.

![Screen Shot 2019-08-29 at 12.38.54 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/03598e1c-dd09-4853-a700-3204eee80e39)

- On INSERT (new record), it follows the same logic as above. (without inserting the change log):
(Notice the record id is 0, only the original lat/longs from CRIS were provided):

![Screen Shot 2019-08-29 at 12.54.13 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/3a6c0638-79d2-498b-89ad-3f112f29650f)

**Comment by sergiogcx** [comment]
Closing, this is taken care of.
