### ISSUE TITLE
ETL: CRIS Process Extracted Data

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-vz-data#45]
We need to actually process the CSV files into a database and Knack. The general task will be to parse each CSV file in a way that does not take up all resources in the server and parse each CSV line into Knack and Postgres. 

- [x] Spin up an RDS Postgres DB
- [x] Work on ruby script that will parse the CSV and UPSERT into Postgres:
- [x] When done, upload CSV files to S3 for archiving or further analysis.
